### ISSUE TITLE
CVSS update for CVE-2024-28064

### ISSUE THREAD

**Issue by delpeter** [cisagov/vulnrichment#106]
The Availability impact in the CVSS score is currently [marked as None](https://github.com/cisagov/vulnrichment/blob/develop/2024/28xxx/CVE-2024-28064.json#L35), but should be High since the files that are accessed through path traversal are then deleted on the server:
https://www.objectif-securite.ch/advisories/totemomail-path-traversal.txt

I actually crashed the Totemomail server by accessing (and unintentionally deleting) the application's JAR file, licensing key and/or database.

Here is the suggested update:

Current CVSS:  `CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N` (base score 9.1)
Updated CVSS: `CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H` (base score 9.8)

**Comment by todb-cisa** [comment]
Availability is always a little tricky/inflated, since if you have file write access for any bug, you quite nearly always have file delete access. So, Integrity:High (with this thinking) almost always also means Availability:High, thus pumping the score, and also, obfuscating those bugs where the /only/ affect is DoS. I'll let @jwoytek-cisa make the call on this one, but for me, I'm not a fan of double-counting C/I/A for these kinds cases. Maybe this case is special, but it's almost never helpful.

(This is not me complaining about @delpeter's report, this is me complaining about CVSS in general.)

**Comment by jwoytek-cisa** [comment]
I looked at this and also asked the analyst who handled this to check it, and we both tend to agree with the A:H score. This will be updated upstream and data should push out to all channels in a little while. 

@todb-cisa regarding your concern, I suppose I can see cases where it is possible to have I:H but not also be able to cause an issue with service availability, but agree that it seems like I:H would also imply a higher availability score in most instances. A bug where the only potential affect is a DoS doesn't seem like it would also get I:H, though, at least due to file r/w/d ability, so it seems like this scoring configuration would not necessarily mask bugs that are only DoS. I may be missing something here, though. Perhaps this is a discussion where @amanion-cisa can lend expertise. 

I'm going to close this as the issue at hand is resolved, but Tod's concerns may warrant further discussion.
