### ISSUE TITLE
Incorrect CPE Assignment & General Strategy

### ISSUE THREAD

**Issue by j-baines** [cisagov/vulnrichment#126]
This is a general issue that I've wondered about since Vulnrichment began assigning their own undocumented CPE. Vulnrichment has assigned many unofficial CPE, for example, consider the CPE for [CVE-2023-4214](https://github.com/cisagov/vulnrichment/blob/f5e4435240a6b2e59a7fc74ce86b9da255966d16/2023/4xxx/CVE-2023-4214.json#L68):

```json
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:scottopolis:apppresser_mobile_app_framework:*:*:*:*:*:*:*:*"
            ],
            "vendor": "scottopolis",
            "product": "apppresser_mobile_app_framework",
            "versions": [
              {
                "status": "affected",
                "version": "0",
                "versionType": "custom",
                "lessThanOrEqual": "4.2.5"
              }
            ],
            "defaultStatus": "unknown"
          }
        ],
```

This CPE isn't [official](https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=scottopolis), as far as I can tell. It's also somewhat odd in that NVD assigned an official CPE to this CVE well before Vulnrichment came into existence (the CVE has not been updated since November 2023). NVD assigned [CVE-2023-4214](https://nvd.nist.gov/vuln/detail/CVE-2023-4214) the following CPE:

```json
        {
          "nodes": [
            {
              "cpeMatch": [
                {
                  "vulnerable": true,
                  "criteria": "cpe:2.3:a:apppresser:apppresser:*:*:*:*:*:wordpress:*:*",
                  "versionEndExcluding": "4.3.0",
                  "matchCriteriaId": "AD310E2F-6759-441A-B798-456927C53D2E"
                }
              ]
            }
          ]
        }
      ],
```

So now we have two conflicting CPEs. One unofficial, but present in the MITRE data (because CISA ADP) and one official present in the NVD data. How does CISA expect users to use the unofficial CPE when they are in conflict with NVD? Does CISA go back and update their CPE to the official versions when NVD catches up? Do these unofficial CPE help or do they cause more confusion? 

I don't think this is rhetorical either. Every day CISA creates a number of unofficial CPE so understanding the strategy and expected use case of this data is certainly valuable.

**Comment by jwoytek-cisa** [comment]
I'm going to loop in @amanion-cisa and @todb-cisa as this is wider question that needs some discussion.

**Comment by j-baines** [comment]
I think maybe my original comment is unclear because I used an older example. Here is a new example (and to be clear, this plays out multiple times every day). On October 22, 2024 CISA ADP assigned the following CPE to CVE-2024-9267:

* https://github.com/cisagov/vulnrichment/blob/025ec2f98296cfef3593594dbdec67a132dfac06/2024/9xxx/CVE-2024-9627.json#L34
* https://cveawg.mitre.org/api/cve/CVE-2024-9627:

Of course, there is no official CPE for this software as it's never appeared in the vulnerability database before. Given that, CISA generated a CPE for the software, which is totally fair and a stated side affect of Vulnrichment. However, three days later, on October 25, NVD assigned the following:

![Image](https://github.com/user-attachments/assets/2b0b1cc1-364c-40ee-ac88-95347c08ecba)

So we find ourselves in the situation I tried to outline in the first post. There is a CISA ADP generated CPE in the mitre.org JSON that says one CPE and NVD says a totally different one. As a consumer of the data, which one should I be using? If I was a consumer of unofficial CISA ADP CPE (and just for clarity, I'm not. Somehow this particular investigation is "for fun"), what the heck am I supposed to do with the NVD CPE? It's a weird territory to navigate and I'm curious what the team has in mind for their consumers.

Either way, I figured I'd try to bring clarity to my original comment.

**Comment by todb-cisa** [comment]
Ah ha. I would expect that if an NVD-sourced CPE surfaces at some point, CISA should adjust/drop ours, similar to how we deal with conflicting CWEs and CVSSes.

**Comment by jwoytek-cisa** [comment]
@todb-cisa I'm adding @amanion-cisa to the assignee list, as I think this needs to be a process change that happens above me, likely coordinated with some automation bits at my level.

**Comment by j-baines** [comment]
> Ah ha. I would expect that if an NVD-sourced CPE surfaces at some point, CISA should adjust/drop ours, similar to how we deal with conflicting CWEs and CVSSes.

Totally reasonable approach. Thanks for the feedback!

**Comment by amanion-cisa** [comment]
Hi @j-baines, two part response. Regarding vulnrichment specifically, the process is to search for and prefer an official CPE in the [dictionary](https://nvd.nist.gov/products/cpe). So for this specific example (​CVE-2023-4214) and any others that clearly have an official CPE, vulnrichment should be corrected. If no official CPE is found, check the somewhat-less-official set of CPEs created by NVD but not yet added to the dictionary (IIRC this is ~800K CPE strings). If no match, create an "unofficial" CPE.

> How does CISA expect users to use the unofficial CPE when they are in conflict with NVD?

> Does CISA go back and update their CPE to the official versions when NVD catches up? Do these unofficial CPE help or do they cause more confusion?

I don't think we have answers yet. Yes, multiple possibly conflicting or duplicate CPE stings would cause confusion. OTOH, having CPE strings at all may be a benefit, for instance, if the NVD doesn't provide them (yet).

Regarding CPE more broadly, the vulnrichment CPE experience has shown (IMO at least) that NVD wasn't initially designed to be used directly by anyone other than the NVD. NVD owns the namespace, and although they welcome CPE submissions, it turns out there is a lot of software in the world, CPE is very based on individual versions (even CPE ranges depend on knowledge of intermediate versions), and there are breaking issues with how CVE implements CPE (see https://github.com/CVEProject/quality-workgroup/issues/12 and https://github.com/CVEProject/cve-schema/issues/321). CPE is, in effect, an worthy attempt to solve the global "software naming" problem, but that problem will probably not be solved by any single entity.

Lastly, what @todb-cisa said, modulo needing the NVD `configurations` JSON to be implemented in CVE JSON, which is in progress.

**Comment by amanion-cisa** [comment]
Specifically for [CVE-2023-4214](https://cveawg.mitre.org/api/cve/CVE-2023-4214), fixed to match the NVD CPE.

The general strategy remains as described above, try to match the NVD CPE Dictionary, or what CPE already exists, or make something up (another better option to making one up would be to use the vendor/supplier-provided CPE, if that exists.
