### ISSUE TITLE
Replication issue between CVE and Vulnrichment on CVE-2024-40711

### ISSUE THREAD

**Issue by todb-cisa** [cisagov/vulnrichment#127]
The Automatable SSVC decision point in this repo, and upstream in CVE, disagree.

In the Vulnrichment repo, we [see](https://github.com/cisagov/vulnrichment/blob/ef99cc9014ea0bb6fde2847e47fc7b1ac4260d81/2024/40xxx/CVE-2024-40711.json#L7C9-L24C19):

```json
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2024-40711",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "yes"
                  },
                  {
                    "Technical Impact": "total"
                  }
                ],
```

So, Automatable: yes

But on CVE.org, we [see](https://www.cve.org/CVERecord?id=CVE-2024-40711) this rendered:

![Image](https://github.com/user-attachments/assets/feb29ee3-3f75-4947-8cbb-bf1fd92a12d2)

So, Automatable: no. 

(For what it's worth, I believe "yes" is correct.)

Looks like there's a disconnect between the two. The timestamp on the Vulnrichment record is newer, but hasn't been replicated up.

**Comment by todb-cisa** [comment]
Interestingly, the vendor's reference has a CVSS statement that disagrees with the CVE text from the issuing CNA.

**Comment by jwoytek-cisa** [comment]
I looked into this and I think I see what happened here. For what it's worth, the CVE Services data is "correct," inasmuch as it is actually the most recent score. The timestamps were skewed here a little due to a CVE record update that caused the Vulnrichment record to appear with the same date as the CVE record update. 

There are a few issues here that will need to look into more closely to determine what the right path forward is to resolve the kind of conflict that caused this discrepancy. 

Vulnrichment repo data should update within the hour and should then match the CVE Services data.

Leaving this open for tracking.

**Comment by jwoytek-cisa** [comment]
Still tracking this and working on some process to help minimize the chances of this happening again in the future.

**Comment by eslerm** [comment]
fwiw, the CVE Program's `cvelistV5` repo has blame history

https://github.com/CVEProject/cvelistV5/blame/main/cves/2024/40xxx/CVE-2024-40711.json

**Comment by todb-cisa** [comment]
This particular instance has been resolved, and also, there is some checking going on on the backend to make sure this doesn't pop up again.
