### ISSUE TITLE
CVE-2024-36905: need clarification why it is set as network attack vector

### ISSUE THREAD

**Issue by joelguittet** [cisagov/vulnrichment#130]
Hello,
I would like to ask a clarification about the CVE-2024-36905. You indicate it is a network attack vector. Can you elaborate why ?
Both [Red Hat](https://access.redhat.com/security/cve/cve-2024-36905) and [AWS](https://alas.aws.amazon.com/cve/html/CVE-2024-36905.html) classify the CVE with a local attack vector. Note I don't know why either.
Thanks for the feedbacks
Joel

PS: NIST currently check for this database to populate their own and so they currently indicate a network attack vector but the CVE is still indicated waiting for analysis. This is the path I followed to open this issue.

**Comment by jwoytek-cisa** [comment]
@joelguittet Thank you for the question. I've forwarded this on to our analysts to check the assessment and provide commentary or changes as needed.

**Comment by solardiz** [comment]
This is also being discussed in a thread on oss-security. It appears to me that besides the attack vector, also the impact is exaggerated:

https://www.openwall.com/lists/oss-security/2024/11/12/4

> The CISA-ADP CVSS vector for this vulnerability specifies that it not only is network-reachable, but also that it has High impact not only on Availability, but also on Confidentiality and Integrity.  This results in a CVSSv3.1 score of 9.8.  Even merely correcting the vector not to claim any Confidentiality and Integrity impact (as a divide-by-zero generally does not have that) would bring the score down significantly.

As to the attack vector, please see the full message referenced above for reasoning on why network-only triggering of this vulnerability (without assistance from a program running locally) is very unlikely (and probably impossible).

**Comment by amanion-cisa** [comment]
First, thank you for the feedback, we do appreciate it and one option is to just accept the emerging consensus on the oss-security thread and change the CVSS vectors. CVSS base vectors become less informative at higher layers (like libraries and kernels) that have many, many possibe uses (and attack vectors and impacts).

To be blunt, understanding these esoteric Linux kernel vulnerabilities is expensive (in time and expertise) and the return-on-investment is typically low. My personal default summary starts at "authenticated local user, under fairly rare conditions, can crash the kernel, and maybe execute arbitrary code if someone spends enough time figuring it out." Or "fuzzing found a crash with evidence of memory corruption, could be induced by a local user." A very naieve interpretation of CVE-2024-36905 is AV:N because of the string "tcp". 

CVSS says to assume the "reasonable worst case." Is it completely impossible to exploit CVE-2024-36905 over the network? Is divide-by-zero (in the kernel) always C:N/I:N/A:H? I'd advise not investing too heavily in any CVSS base scores, especially for poorly understood vulnerabilities like CVE-2024-36905. Or create your own score if you believe or understand differently.

Is it "reasonable worst case" that a remote, unauthenticated attacker can crash the kernel? Or is that "unreasonable" and instead a local authenticated user can crash the kernel? I think in either case I'd be willing to accept that divide-by-zero means C:N/I:N/A:H.

**Comment by amanion-cisa** [comment]
Here's a proposed CVSS 3.1 vector: https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H

**Comment by solardiz** [comment]
I suggest going with Red Hat's `CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H` giving a score of 5.5. The difference is in "attack complexity", yours has it as High, RH has as Low. I think if we treat this as local, the complexity reasonably becomes low because it is not hard to run a pre-written exploit locally (such as the program I think syzbot found to trigger this bug). Thank you very much!

**Comment by joelguittet** [comment]
@solardiz @amanion-cisa thanks for commenting here! So what should be the next step ? PR on this repo ? Something else ? Thanks for the guidance!

**Comment by amanion-cisa** [comment]
We can't really accept PRs because the data is generated upstream, but we made the changes discussed in this issue (the Red Hat CVSS score), see:

https://cveawg.mitre.org/api/cve/CVE-2024-36905

https://github.com/cisagov/vulnrichment/blob/develop/2024/36xxx/CVE-2024-36905.json (updates hourly).

Thanks for the feedaback!

**Comment by solardiz** [comment]
Thank you very much, @amanion-cisa!

Meanwhile, NVD reports two new CVSS vectors/scores for this CVE - one from NVD itself, the other from Microsoft CNA. Both look wrong to me - besides the attack vector issue, they claim high confidentiality impact and no availability impact. Indeed, not something to fix in here, but just another illustration of how hard it is to correctly score vulnerabilities without thorough analysis of each one, and how skeptical we should be about the scores.
