### ISSUE TITLE
Create some boilerplate text about pull requests to CVE entries

### ISSUE THREAD

**Issue by todb-cisa** [cisagov/vulnrichment#78]
Many people seem to enjoy editing CVE entries directly to demonstrate what they'd like to see changed -- this is especially true for people who disagree with ADP opinions on CPEs, CWEs, and CVSS scores. And, while we definitely want to hear about these other opinions, PRs tend to see this kind of workflow:

- External contributor forks and edits and pull requests, all in the usual way
- Maintainer sees the PR, might have a little discussion, and possibly agrees with the external assessment.
- If agreed, maintainer might land the PR, or might not, because the actual change needs to happen to the relevant metric on the backend, and publish *that* fix.
- If the provided PR doesn't land, the contributor doesn't get the nice little dopamine hit from having a successfully merged PR.
- If the provided PR does land, it ends up being kind of meaningless in a practical sense, since it'll be overwritten by the next scheduled push from the backend. So, at best, this is a NOP workflow. At worst, merge conflicts happen.

The easy answer is to reject all PRs to CVEs, but that kind of sends a message of "thanks, don't care."

Perhaps some guidance in a CONTRIBUTING.md doc about how to use PRs? Basically, we should outline that we definitely can accept PRs to pretty much anything that's **not** a CVE entry, and cannot practically accept PRs to CVEs.(but can perform edits and push) 

Up for discussion. I don't want to rob people of internet points, but I also don't want to encourage broken and risky workflows.

**Comment by todb-cisa** [comment]
And as for the title of this issue, not only should this be documented in CONTRIBUTING.md, but there should be some boilerplate text for when people invariably ignore CONTRIBUTING and try to edit CVEs directly anyway.

**Comment by todb-cisa** [comment]
Tagging in @MaineK00n and @j-baines who seem to be the most prolific CVE PR'ers for input/feedback/agrument.

**Comment by MaineK00n** [comment]
I like Pull Request because it can be clearly shown how to change it.
If your workflow is not good to submit with Pull Request, I want you to propose a data correction request method that is good for workflows.
Anyway, for me, it is more important to be more accurate and useful than the number of contributions.

**Comment by todb-cisa** [comment]
@MaineK00n I agree, a PR makes it easy to see exactly the change. Would it be acceptable, then, to say "Feel free to create PRs for CVEs to illustrate the change you want to see, but don't be surprised if the PR is closed with a comment instead of merged" or something nicer?

**Comment by MaineK00n** [comment]
@todb-cisa 
I don't mind if you close the pull request with a comment instead of merging it, as long as the data is fixed quickly anyway.
However, as you were initially concerned, I think it is important to provide a visible achievement or experience, such as showing contributions, in order to gain the support of many users.

**Comment by todb-cisa** [comment]
> I think it is important to provide a visible achievement or experience

Yeah, we're trying to weigh that against the threat of merge conflicts. So far the volume isn't making it too hard. Maybe we can just commit to a PR merge followed by some flavor of `git merge --strategy-option ours` to blow past any possible conflicts.

For documentation, I can say that we'll favor merging PRs, but note the overwrite likelihood, and state that we'll occasionally merely close and fix externally. But, that's really only for CVE JSON files -- other areas are happy to take PRs.

@jwoytek-cisa, how's this grab you?

**Comment by jwoytek-cisa** [comment]
@todb-cisa I think that's fine. I still think it would be nice to have some words in CONTRIBUTING.md or README.md to help explain the overwrite/merge issue so that I (or whoever is handling the PR that day) doesn't feel the need to have those words constantly ready in a paste buffer somewhere, and to help contributors understand that in some cases, we may still have to close a PR with a comment because a merge would introduce data artifacts that would require another republish from upstream to fix.

**Comment by todb-cisa** [comment]
All right. My goal is to write this down in CONTRIBUTING.md, and also repeat it in the PR template [per GitHub docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) before the holiday. Thanks all for the discussion.

**Comment by todb-cisa** [comment]
Decided not to scope-creep this request, and just document how we handle PRs in PR #88. I'll leave off the business of fixing up the boilerplate language in GitHub issues to another day if there's serious complaints about it (the default that's running now seems fine, if a bit verbose).
