### ISSUE TITLE
Add Package URLs

### ISSUE THREAD

**Issue by pombredanne** [cisagov/vulnrichment#89]
# 💡 Summary #

I would like to see Package URLs (aka. PURL) enriching vulnerabilities

## Motivation and context ##

The CPEs created here may not match the CPE @ the NVD and CPEs are not easy to work with when doing modern software development using open source packages and libraries. With a PURL, a package as detected in a scan can be use directly to lookup a vulnerability. Getting a PURL in the enriched CVE would be a great help for everyone, and would further help with use of this data set with SBOMs that most often use PURL as a package identifier. 

## Acceptance criteria ##

How do we know when this work is done?

- [ ] affected PURLs are published when a CVE affects an open source package

**Comment by todb-cisa** [comment]
So rather than having this hang around, I figure I may as well comment.

Listing pURLs is great, and people should definitely do it. In fact, in [Vulnogram](https://vulnogram.github.io/#editor), it's a top-level attribute that CNAs can use to point to the affected product.

![Screenshot of Vulnogram](https://github.com/user-attachments/assets/c24bc768-e668-4456-8613-eabdc90386bc)

So, 💯 , yes, please do. It's a capability that all CNAs have today.

That said, adding pURLs is out of scope for the CISA ADP today. Perhaps that will change as the ADP program matures at CVE, or if there's overwhelming support for pURLs as part of the CISA ADP, or some other ADP can roll in and be scoped specifically for pURLs.

So, I'm going to close this issue, since there's nothing really we can do with it today. This won't halt future comments or anything, and we can still talk about it (and/or investigate using GitHub Discussions for stuff like this). But right now, we don't have plans for supporting this.

**Comment by pombredanne** [comment]
@todb-cisa Thanks for your reply!

You wrote:

> Listing pURLs is great, and people should definitely do it. In fact, in Vulnogram, it's a top-level attribute that CNAs can use to point to the affected product.

I am not sure that these attributes e.g., "Package collection URL" and "Package name" are an actual PURL as specified at https://github.com/package-url/ ... (PS: I am the creator of PURL), but there again that would be likely out of your purview.
