### ISSUE TITLE
Clearly reference SSVC version source

### ISSUE THREAD

**Issue by todb** [cisagov/vulnrichment#90]
In the SSVC section of the ADP container, there's a `version` field which states that it's version `2.0.3.`. However, the real [releases of SSVC](https://github.com/CERTCC/SSVC/releases) don't appear to include anything called 2.0.3. There's 2.0, then 2.1, then suddenly jumps up two thousand and twenty-two versions to 2024.3.

Maybe that's the intended version number?

Anyway, it's unclear to me. It would be nice to keep a reference to that somewhere in this repo, possibly the readme, possibly in some dependency doc.

**Comment by jwoytek-cisa** [comment]
@todb the [SSVC Computed Schema](https://github.com/CERTCC/SSVC/blob/main/data/schema/SSVC_Computed.schema.json) as of the date of this comment defines the version field like this:

>Version of the SSVC that was used in this decision.  This version is of the semver format major.minor.patch The major.minor should identify SSVC version being used.  The specific tree being used should be in the patch number For example: \"Applier Tree 2.0.3\" would be the identity of the version of SSVC being \"2.0\" and the version of the Applier Tree to be \"3\"."

As far as we are aware, the CISA Coordinator tree version is 3, and is using SSVC version 2.0, hence 2.0.3. 

If the tree is updated to conform to 2024.3, the full version string would be 2024.3.3. It looks like the SSVC major version switched to current year instead of a simple index after 2.1.  

It is probably worth the time to check to see what version of the decision tree is currently in use to be sure that our version numbers are sync'ed up across processing systems.
