### ISSUE TITLE
Why is the CISA-ADP severity rating so high for something considered low by the vendor? (CVE-2024-5535)

### ISSUE THREAD

**Issue by pcreager23** [cisagov/vulnrichment#93]
# 🐛 Summary #

CISA-ADP has CVE-2024-5535 as a **9.1 Critical**, but the vendor considers it a Low severity issue.

Ref: https://nvd.nist.gov/vuln/detail/CVE-2024-5535

## Expected behavior ##

Per OpenSSL:
> OpenSSL Security Advisory [27th June 2024]
> SSL_select_next_proto buffer overread (CVE-2024-5535)
> **Severity: Low**

Ref: https://openssl-library.org/news/secadv/20240627.txt

**Comment by todb-cisa** [comment]
Thanks for asking, @pcreager23! The CVSS score that CISA calculated was [CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H](https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H) which, indeed, comes out to a 9.1. Of course, this is the worst-case scenario, as this bug is in a bit of library code, and not a straightforward application bug.

OpenSSL is absolutely correct that the conditions for exploitation are going to be pretty rare. You have to configure your implementation to "directly call the SSL_select_next_proto function with a 0 length list of supported client protocols."

But, if you do do that, that's where this seemingly high CVSS score comes in -- the attacker needs no authentication, the vector is over a general network, and the crashing condition is trivial to elicit, which can give the attacker good OpenSSL secrets (Confidentiality impact of "high") and/or crash the service (Availability impact of "high").

So, that's why. Library bugs, in my experience, tend to score pretty high, since you're looking at them in isolation, but a severity determination in your environment should account for the realities of your particular implementations. This bug appears to me to be easily avoidable in your software design phase.

**Comment by pcreager23** [comment]
Thanks Tod.
