### ISSUE TITLE
CVSS 4.0 Usage

### ISSUE THREAD

**Issue by nicpenning** [cisagov/vulnrichment#98]
Greetings! This sounds like an interesting project for sure.  

There seems to be some overlap between this project and a some of the improvements to CVSS 4.0. Will CISA adopt and implement CVSS 4.0 during the enrichment process or only include CVSS 4.0 enriched data if it already exists? Are there any CVEs that include CVSS 4.0 scores?

**Comment by todb-cisa** [comment]
I'll let @amanion-cisa or @jwoytek-cisa comment on the the "are there any CVSS 4.0 in the data yet?" question (I don't know off hand), but right now, we have no plans in place to update to CVSS 4.0. It's a bit of a chicken and egg situation -- we're not doing CVSS 4.0 because we haven't seen a lot of pickup in the industry or community around it, but also, I think that's the explanation / excuse everyone else is using, as well.

I haven't seen a particularly compelling reason to transition to CVSS 4.0.

**Comment by amanion-cisa** [comment]
Some CNAs are providing CVSS 4.0, Juniper for example: https://cveawg.mitre.org/api/cve/CVE-2024-39565.

Rough count: 1385 CVSS 4.0 scores out of 22257 CVE records in vulnrichment data (records published since 15 Feb), so ~6%.

```
   9 ABB
   3 ASRG
   2 Baxter
   1 Bitdefender
  13 CERT-In
  23 CERT-PL
   3 Carrier
   1 Checkmk
  10 Citrix
   4 ConcreteCMS
   1 CoolKit
  11 CyberDanube
   7 DIVD
   1 Docker
   1 Document Fdn.
   3 ESET
   2 Fortra
   4 GandC
   9 GitHub_P
   1 Gitea
  10 Google
   1 HYPR
   1 Hanwha_Vision
   2 Hitachi Energy
   1 INCIBE
   1 JAMF
   1 KNIME
   4 LGE
   1 LY-Corporation
   3 M-Files Corporation
   2 Microchip
   5 NCSC.ch
   2 NI
   1 NLOK
   6 Nozomi
   2 ONEKEY
   8 OpenText
   4 PandoraFMS
   2 Perforce
   3 Ping Identity
   1 ProgressSoftware
   1 PureStorage
  22 Rockwell
   3 SN
   2 SNPS
   1 Sonatype
   6 TR-CERT
 807 VulDB
   2 WDC PSIRT
   3 Yugabyte
   3 ZUSO ART
   1 blackberry
   6 cisa-cg
   1 elastic
   9 f5
  71 icscert
  59 intel
   5 jci
  78 juniper
   2 netflix
  11 palo_alto
   1 rapid7
   3 samsung.tv_appliance
 101 siemens
  11 symantec
   1 tibco
   5 upKeeper
```

**Comment by nicpenning** [comment]
Excellent, thank you! It is evident that CVSS 4.0 exists!
